export const UserActionTypes = {
  USER_SET: "USER_SET",
  USER_SET_SETTINGS: "USER_SET_SETTINGS",
  USER_SET_LOCATION: "USER_SET_LOCATION",
  USER_RESET_LOCATION: "USER_RESET_LOCATION",
  USER_SET_AVAILABILITY_GENERAL: "USER_SET_AVAILABILITY_GENERAL"
}
